export default 
{ "height":14,
 "layers":[
        {
         "data":[3, 6, 7, 4, 4, 3, 3, 6, 4, 3, 3, 7, 6, 4, 4, 3, 3, 4, 4, 3, 3, 4, 6, 4, 3, 6, 5, 5, 3, 4, 4, 6, 7, 5, 7, 3, 5, 5, 3, 6, 4, 3, 7, 3, 7, 3, 7, 5, 4, 7, 4, 4, 6, 5, 7, 7, 6, 5, 5, 4, 6, 6, 3, 4, 7, 3, 4, 7, 3, 6, 7, 7, 3, 5, 4, 7, 7, 3, 5, 6, 4, 5, 5, 7, 6, 7, 7, 4, 4, 6, 3, 4, 4, 5, 7, 3, 6, 4],
         "height":14,
         "name":"fall-pieces",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":7,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.0.2",
 "tileheight":415,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"pieces",
         "spacing":0,
         "tilecount":9,
         "tileheight":415,
         "tiles":
            {
             "0":
                {
                 "image":"..\/..\/pieces\/booster01.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "1":
                {
                 "image":"..\/..\/pieces\/booster02.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "2":
                {
                 "image":"..\/..\/pieces\/piece01.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "3":
                {
                 "image":"..\/..\/pieces\/piece02.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "4":
                {
                 "image":"..\/..\/pieces\/piece03.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "5":
                {
                 "image":"..\/..\/pieces\/piece04.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "6":
                {
                 "image":"..\/..\/pieces\/piece05.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "7":
                {
                 "image":"..\/..\/pieces\/piece06.png",
                 "imageheight":415,
                 "imagewidth":415
                },
             "8":
                {
                 "image":"..\/..\/pieces\/piece07.png",
                 "imageheight":415,
                 "imagewidth":415
                }
            },
         "tilewidth":415
        }],
 "tilewidth":415,
 "type":"map",
 "version":1,
 "width":7
}