var windowsSettings = windowsSettings || {};



windowsSettings.appName = 'Candy Crush Friends Saga';

windowsSettings.carouselImg = [
	// "1.jpeg",
	// "2.jpeg",
	// "3.jpeg",
	// "4.jpeg",
	// "5.jpeg",

	"1.png",
	"2.png",
	"3.png",
	"4.png",
	"5.png",

];


windowsSettings.defaultLang = "en";
windowsSettings.translations = {
    'Download': {
        en: "Download",
        de: "Download",
        fr: "T�l�charger",
        it: "Scarica",
        es: "Descargar",
        pt: "Baixar",
        ca: "Descarregar",
        tr: "Indir",
        nl: "Download",
        sv: "Ladda ner",
        id: "Download",
        no: "Nedlasting",
        nb: "Nedlasting",
        nn: "Nedlasting",
        pl: "Pobierz",
        da: "Hent",
        hr: "zbirka",
        sq: "Shkarko",
        sl: "prenesi",
        zu: "ukulanda",
        ga: "�osl�d�il",
        is: "s�kja",
        hu: "Let�lt�s",
        et: "lae alla",
        eu: "deskargatu",
        fi: "ladata",
        sw: "kupakua",
    },
    'Play!': {
        en: "Play!",
        de: "abspielen!",
        fr: "jouer!",
        it: "giocare!",
        es: "�Jugar!",
        pt: "Toque!",
        ca: "Jugar!",
        tr: "oyun!",
        nl: "spelen!",
        sv: "spela!",
        id: "bermain!",
        ro: "Joaca!",
        no: "spille!",
        nb: "spille!",
        nn: "spille!",
        ms: "Bermain!",
        da: "Spille!",
        hr: "Igra!",
        sq: "Luaj!",
        sl: "Igraj!",
        az: "Oynamaq!",
        zu: "Dlala!",
        ga: "Seinn!",
        is: "Leika!",
        hu: "J�t�k!",
        mt: "Play!",
        et: "M�ngi!",
        eu: "Jokatu!",
        fi: "Pelata!",
        sw: "Jaribu!",
    },
    'Play': {
        en: "Play",
        de: "abspielen",
        fr: "jouer",
        it: "giocare",
        es: "�Jugar",
        pt: "Toque",
        ca: "Jugar",
        tr: "oyun",
        nl: "spelen",
        sv: "spela",
        id: "bermain",
        ro: "Joaca",
        no: "spille",
        nb: "spille",
        nn: "spille",
        ms: "Bermain",
        da: "Spille",
        hr: "Igra",
        sq: "Luaj",
        sl: "Igraj",
        az: "Oynamaq",
        zu: "Dlala",
        ga: "Seinn",
        is: "Leika",
        hu: "J�t�k",
        mt: "Play",
        et: "M�ngi",
        eu: "Jokatu",
        fi: "Pelata",
        sw: "Jaribu",
    },

    'download_icon.png': {
    //   en: '',
    //   ja: 'ja-',
    //   zh: 'zh-',
    },
};
